### ISSUE TITLE
How to install pymacs on windows

### ISSUE THREAD

**Issue by shuweicn** [pinard/Pymacs#60]
C:\Users\tree\Desktop\Pymacs [master]> make -v
GNU Make 3.82
Built for x86_64-w64-mingw32
This program is built by Equation Solution http://www.Equation.com
for Windows.
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
C:\Users\tree\Desktop\Pymacs [master]>

C:\Users\tree\Desktop\Pymacs [master]> make
python pppp -C ppppconfig.py Pymacs.py.in pppp.rst.in pymacs.el.in pymacs.rst.in contrib tests
Traceback (most recent call last):
  File "pppp", line 425, in <module>
    main(_sys.argv[1:])
  File "pppp", line 127, in main
    self.transform_all_files(argument)
  File "pppp", line 244, in transform_all_files
    input, open(input), open(output, 'w').write)
  File "pppp", line 330, in transform_file
    self.each_substituded_line(lines)):
  File "pppp", line 412, in each_substituded_line
    for line in lines:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 119: illegal multibyte sequence
make: *_\* [prepare] Error 1
C:\Users\tree\Desktop\Pymacs [master]>

**Comment by npostavs** [comment]
Is this a dup of #57?
